PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;
CREATE TABLE species (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    common_name TEXT,
    category TEXT,
    scientific_name TEXT,
    pronunciation TEXT,
    type TEXT,
    height TEXT,
    spread TEXT,
    spacing TEXT,
    habit TEXT,
    culture TEXT,
    uses TEXT,
    problems TEXT,
    notes TEXT
);
INSERT INTO species VALUES(1,'AGERATUM','annuals-and-perennials','Ageratum houstonianum','ag-er- RAH -turn huse-tone-ee-AN-um','Annual—Morning Sun/Part Shade','8"-12"','12"-15"','9"-12"','Round, fluffy lavender or white flowers all summer. Rounded overall shape, heart-shaped leaves.','Does well in properly prepared beds. Avoid overwatering.','Small groupings or borders. Good in pots.','Spider mites in the heat of summer.','Likes cool weather best. ');
INSERT INTO species VALUES(2,'ALYSSUM','annuals-and-perennials','Lobularia maritima','lob-ew-LAR-ee-ah ma-RI-tim-ah','Annual—Sun','3"-4"','9"-12"','6"','Low-growing, small delicate flowers of white and lavender that bloom in summer.','Requires little care but is damaged easily by foot traffic and pets. Any soil, relatively drought tolerant. Likes cool weather. Can take light frost.','Rock gardens, pockets in stone walls, small accent areas of annual color.','Few if any.','Native to Turkey. Purple heart is also shown. ');
INSERT INTO species VALUES(537,'PLUM, PURPLE','trees','Prunus cerasifera','PROO-nus ser-as-SIFF-eh-ruh','Deciduous—Sun/Shade','20''','15''','12''—15''','Small ornamental tree with bronze or purple foliage after pink spring flowers.','Does okay in any soil, moderate maintenance. Needs good drainage, as most trees do.','Ornamental garden tree, summer color.','Borers, freeze damage, and root disease. Short-lived tree.','''Krauter Vesuvius'' is the most colorful and my favorite. Native to Asia. Don''t invest a lot in this tree. ');
INSERT INTO species VALUES(538,'POPLAR, LOMBARDY','trees','Populus nigra ''Italica''','POP-pew-lus Nl-gra eh-TAL-eh-kuh','Deciduous—Sun','70''','10''','','Slender and extremely fast-growing junk tree. Very short-lived.','Grows anywhere for a while.','A good way to waste your money.','Borers, root rot, short life, trunk canker, scale.','Usually not healthy and never desirable—do not plant! Native to Europe and Asia. ');
INSERT INTO species VALUES(539,'REDBUD','trees','Cercis canadensis','SER-sis kan-ah-DEN-sis','Deciduous—Sun/Shade','30''','30''','15-20''','Wide-spreading ornamental, purple or white spring color, yellow fall color.','Easy to grow in any soil, drought tolerant.','Ornamental garden tree, understory Flowers are edible.','Borers, leaf rollers.','White variety seems healthier than the purple native. Crinkled-leaf Mexican variety is the most drought tolerant, ''Oklahoma'' has dark green glossy foliage, and ''Forest Pansy'' has red-purple foliage in summer. Native to the eastern half of Texas. Lombardy Poplar ');
INSERT INTO species VALUES(540,'RED WOOD, DAWN','trees','Metasequoia glyptostroboides','met-ah-see-QUOI-ah glip-toe-stro-BOY-deez','Deciduous—Sun','80''','30''','20-40''','Narrow and pyramidal, branches angle up rather than grow perpendicular like those of bald cypress. Fine, lacy foliage, reddish brown fall color.','Likes deep, slightly acid soils best, but adapts to our alkaline soils quite well. Several large specimens are doing well in Dallas.','Specimen garden tree, backdrop.','Chlorosis and foliage burn in shallow soils.','An ancient tree native to China and Japan. Distinctive and worth trying. ');
INSERT INTO species VALUES(541,'ROYAL PAULOWNIA (Princess or Empress Tree)','trees','Paulownia tomentosa','pa-LONE-ee-ah toe-men-TOSE-ah','Deciduous—Sun','50''','50''','30-50''','Lives in East Texas sandy acid soils. Often grows as an understory tree. Does not adapt to any other soil. Frequently found along fence lines where the seeds have been planted by birds. Beautiful red fall color and spicy, aromatic bark and leaves. All three leaf shapes can be found on the tree at the same time. Leaves are dark green on top, paler beneath. Fall color can range from orange to pinks, salmons, and dark reds.','Easy to grow as long as you have nice sandy acid soil. In that situation it grows quickly, especially when young. It spreads by rhizomes to create mottes or groves. It is very sensitive to physical disturbance in the root system.','Shade tree for sandy acid soils. Medium-sized shade tree.','Some insect attacks and root rot in heavy clay soil.','Dried sassafras leaves are used to make file, a Creole ingredient used in gumbos and other dishes. Aromatic roots were once used to make teas, but are now considered toxic. ');
INSERT INTO species VALUES(542,'SOAPBERRY (Indian Lilac)','trees','Sapindus drummondii','sap-IN-dus druh-MUN-dee-eye','Deciduous—Sun/Part Shade','40''','30''','20-40''','Foliage similar to Chinese Pistachio. White flower clusters in spring, golden fall color, and winter berries; light gray bark and brittle wood.','Easy to grow anywhere. Drought tolerant. Low fertilization requirements.','Shade tree.','Hard to transplant. Not a good tree to invest much in.','Berries are used as a soap in Mexico. Native to western, central, and southwestern United States. ');
INSERT INTO species VALUES(543,'SWEETGUM','trees','Liquidambar styraciflua','lick-wid-AM-bur sty-rah-SIFF-flu-ah','Deciduous—Sun/Part Shade','70''','30''','20-30''','Vertical, cone-shaped, spreading with age. Red, salmon, orange, and yellow fall color. Stiff branching. Round spiny seedpods.','Needs deep, moist soil and prefers sandy acid conditions—hates solid rock. Quite easy to transplant if given ample water.','Shade tree, great fall color.','Chlorosis and dry, rocky soil. Seedpods are considered a nuisance by many people, but they don''t bother me.','Native to East Texas and other sandy soil areas. Will grow much larger in sandy acid soils. Cultivars such as Talo Alto'' and ''Burgundy'' have excellent fall color but are much more problematic and not recommended. ');
INSERT INTO species VALUES(544,'SYCAMORE (Plane Tree)','trees','Platanus occidentalis','PLAH-ta-nus ok-si-den-TALL-is','Deciduous—Sun','90''','70''','','Fast-growing, with large fuzzy leaves, white and gray flaky bark, yellowbrown fall color.','Anywhere, easy at first.','Shade. The white trunks and limbs are lovely.','Messy leaves that take a long time to break down. Anthracnose, leaf spot, aphids, scale, bagworms, borers, and other problems. Destructive root system.','Poor choice. The London plane tree (P. x acerifolia) is supposed to be healthier, but I still don''t recommend it. ');
INSERT INTO species VALUES(545,'TALLOW, CHINESE','trees','Sapium sebiferum','SAY-pee-um seb-eh-FARE-um','Deciduous—Sun','30''','30''','','Fast-growing, short-lived, poor-quality shade tree. Yellow to red fall color and white berries in winter.','Grows easily but not for a long time.','Temporary tree. Excellent fall and winter color.','Freeze damage, borers, cotton root rot, and short life. Wildly selfpropagating in moist soil environments.','I used to mistakenly recommend this tree, but there are lots of better choices. Native to China and Japan. ');
INSERT INTO species VALUES(546,'TEXAS MOUNTAIN LAUREL (Mescal Bean)','trees','Sophora secundiflora','so-FORE-uh se-kune-di-FLOOR-uh','Evergreen—Sun/Part Shade','20''','10''','8''-15''','Slow-growing, dense foliage, bushy unless trimmed into tree form. Fragrant, purple, wisteria-like flowers in spring. They actually smell like grape soda.','Any well-drained soil. Moderate to low water and feeding requirements.','Specimen ornamental tree or large shrub. Drought-tolerant gardens. Can be grown in containers.','Winter damage in the northern parts of the state.','Great in Central Texas but needs some protection in North Texas. Native to southwestern United States, Texas, and Mexico. ');
INSERT INTO species VALUES(547,'TREE OF HEAVEN','trees','Ailanthus altissima','eye-LAN-thus all-TISS-eh-mah','Deciduous—Sun','50''','20-40''','20-30''','Inconspicuous green flowers, followed by large clusters of reddish brown winged seeds from September to October. Upright, extremely tolerant of the harshest conditions, including drought, heat, wind, and lousy soil.','Easiest tree in the world to grow.','Grows where nothing else will grow.','Can become an obnoxious weed. Also listed as Ailanthus glandulosa.','Often grows in urban areas from cracks in concrete. ');
INSERT INTO species VALUES(548,'TULIP TREE (Tulip Poplar)','trees','Liriodendron tulipifera','lir-ee-ah-DEN-dron too-li-PIF-err-ah','Deciduous—Sun','70''','40''','30-40''','Straight trunk, smooth bark, leaves shaped like tulips, yellow fall color. Interesting yellow and orange flowers in late spring but sometimes hard to see. Flowers will sometimes cover the entire tree.','Grows well in any deep, well-drained soil. Does not like rock. High water requirement in heat of summer.','Shade tree.','Leaf drop in mid to late summer.','Also called yellow poplar and whitewood. Native to midwestern, northeastern, and southeastern United States. ');
INSERT INTO species VALUES(549,'VIBURNUM, RUSTY BLACKHAW (Black Haw)','trees','Viburnum rufidulum','vi-BUR-num rue-FID-you-lum','Deciduous—Sun/Shade','20''','20''','10''—20''','Beautiful shrubby tree, with glossy leaves, white flower clusters in spring, reddish fall color, and blue-black berries late summer. Can grow to 40'' in deep soil.','Easy to grow but not always easy to transplant. Extremely drought tolerant.','Specimen garden tree, understory tree, background mass planting. Excellent small tree for sun or shade. Will have the best color in full sun.','Few if any—practically maintenance free.','Great shrub or little tree. Native to Texas and Oklahoma. This is one of my favorite trees. ');
INSERT INTO species VALUES(550,'VITEX (Lilac Chaste Tree)','trees','Vitex agnus-castus','Vl-teks AG-nus CAST-us','Deciduous—Sun','20''','25''','15''-20''','Spreading, usually multistemmed, brittle wood, not long-lived. Purple or white flowers in early summer. Nicely textured foliage.','Easy to grow in most any soil, drought tolerant.','Summer flowers, foliage texture.','Short life, freeze damage, and partial dieback.','Native to Europe and Asia. Should not be used as a primary tree but rather as a secondary tree for special interest. Some people mistake the foliage for marijuana. ');
INSERT INTO species VALUES(551,'WALNUT, BLACK','trees','Juglans nigra','JEW-gluns Nl-gra','Deciduous—Sun','50''','50''','20-50''','Open-branching character, large distinctive leaves with evenly sized and arranged leaflets on each side of stem. Yellow fall color. Dark bark. Moderate to slow growth.','Likes deep soil, good drainage. Although tolerates alkaline soil, likes a more neutral soil.','Shade tree. Delicious nuts.','Roots give off a toxin harmful to some other plants, especially tomatoes and others in nightshade family.','Nut is almost all structure and little meat—but delicious. Native to the southern United States. ');
INSERT INTO species VALUES(552,'WAX MYRTLE','trees','Myrica cerifera','MY-ruh-kuh sir-RIFF-eh-ruh','Evergreen—Sun/Part Shade','15''','10''','8''-12f','Golden yellow and green male and female flowers on different plants. Flowers from March through April. Fruit of the female plants are small blue drupes clustered along the stems. Moderately fast-growing and spreading, with many small medium green leaves, blue-gray berries in fall. Aromatic foliage dotted above and below.','Easy to grow in any soil, drought tolerant.','Specimen garden tree, evergreen background. Good alternative to yaupon holly.','Brittle wood, suckers.','Birds like the berries. M. pusilla, dwarf wax myrtle, is a good dwarf form that works as a shrub, although not as tough as the larger plant. Native to the southern states and the eastern half of the United States. ');
INSERT INTO species VALUES(553,'WILLOW, DESERT','trees','Chilopsis linearis','KY-lop-sis lin-ee-ERR-is','Deciduous—Sun','30''','25''','15''-20''','Open branching; delicate foliage; lavender, pink, or white orchidlike blossoms in summer. No fall color to speak of.','Easy to grow in any soil, drought tolerant. Does better with more water.','Specimen garden tree, summer color.','Brittle wood and a little wild-looking for some gardens.','Good small ornamental tree, should be used more. Native to southwestern United States. ');
INSERT INTO species VALUES(554,'WILLOW, WEEPING','trees','Salix babylonica','SAY-lix bab-eh-LON-eh-kah','Deciduous—Sun','40''','30''','20''-40''','Graceful, fast-growing. First tree with leaves in spring, last to lose them in fall—almost evergreen. Dense, fibrous root system.','Easy to grow in any deep soil, high water needs.','Softening effect, edges of lakes and streams, temporary tree.','Brittle wood, borers, cotton root rot, short life.','Corkscrew willows (S. matsudana ''Tortuosa'') are more upright, with twisted limbs and branches. Root problems are actually worse on other trees such as mulberry and sycamore. The native black willow (S. nigra) is not a very good landscape tree. White weeping willow (S. alba) has yellow stems. Blue weeping willow (S. blanda) is supposed to be a healthier variety. People are tempted to stake young trees, but it''s a bad idea. ');
INSERT INTO species VALUES(555,'WITCH HAZEL','trees','Hamamelis virginiana','ham-ma-MAY-liss ver-gin-ee-AN-ah','Deciduous—Sun/Part Shade','10-20''','8-10''','8''-10''','Shrubby plant or small, open-growing tree. It grows to a maximum height of about 20'', with single or multiple trunks and an irregularly shaped top. Foliage and flowers are distinctive, and the yellow fall color is usually quite good. Golden yellow flowers bloom in the fall and winter after the leaves have fallen. Flowers of some species have a red or purple cast at the base. Fruit and flowers form simultaneously. Fruit ripens in the second season.','Easy to grow in various well-drained soils. It works very well as an understory plant, but can take full sun as well.','Interesting small tree with herbal uses.','Few exist, other than scarce availability in the nursery trade.','Wonderful little tree that should be planted more often. The name comes from the fact that dousers, or diviners, like to use this plant for finding water. The seeds are edible, and the leaves are used in herb teas. The seeds are also excellent bird food. ');
DELETE FROM sqlite_sequence;
INSERT INTO sqlite_sequence VALUES('species',1110);
COMMIT;
